services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: jwt_refres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    restart: always
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: npm start

volumes:
  postgres-data:
